server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  # Handle SPA routing by redirecting all not-found requests to index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
